spring:
  datasource:
    url: jdbc:h2:mem:taskmanagerdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: test1234
    driver-class-name: org.h2.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
