server:
  port: 8081
  servlet:
    context-path: /taskmanager


jwt:
  private-key: classpath:keys/private_key.der
  public-key: classpath:keys/public_key.der
  expiration: 3600000

spring:
  application:
    name: taskmanager
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:taskmanagerdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: test1234
    driver-class-name: org.h2.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
